const copy={
en:{home:'Home',about:'About',writings:'Writings',poetry:'Poetry',language:'Language',heroNote:'WITHIN EVERYONE / WITHOUT YOU',enter:'Explore TASP',aboutKicker:'THE IDEA BEHIND TASP',introTitle:'An inquiry into<br><em>being human.</em>',introText:'A personal intellectual laboratory for exploring how we think, feel, believe, and make meaning. Here, an observation becomes a question. A question becomes an investigation. And an investigation becomes something we can examine together.',introSecondary:'For the curious, the reflective, and anyone who finds a little of themselves in what they read.',aboutMore:'More about TASP',observe:'Observe',question:'Question',investigate:'Investigate',understand:'Understand',subjectsKicker:'FOLLOW YOUR CURIOSITY',subjectsTitle:'Where would you like to begin?',human:'Human experience',psychology:'Psychology',philosophy:'Philosophy',spirituality:'Spirituality',writingsKicker:'IDEAS TO SPEND TIME WITH',selectedWritings:'The writings.',allWritings:'All writings',threadsKicker:'OBSERVATION, STILL UNFOLDING',threadsTitle:'From a moment to a question.',threadsText:'Two connected explorations, each moving through Observe, Question, and Develop.',poetryKicker:'A DIFFERENT WAY OF KNOWING',poetryTitle:'Some things<br>arrive as <em>poetry.</em>',poetryText:'A quieter space for the things that are felt before they are understood.',visitPoetry:'Enter the poetry collection',poemQuote:'Some chapters are loud.<br>Others are silent.<br>Silence isn’t loss—<br><em>it’s transformation.</em>',poemCredit:'FROM “A PHASE, NOT AN ENDING”',footerLine:'Observe carefully. Question honestly.<br>Understand before concluding.',notion:'Explore on Notion',backTop:'Back to top ↑',read:'Read the essay',readThread:'Follow the inquiry',thread:'Thread',stages:'OBSERVE · QUESTION · DEVELOP',minutes:'min read',close:'Close reading view',sourceNote:'Original English text. The full translation of this piece is being prepared.',originalPoem:'Original poem in Romanized Hindi / Urdu.',poemRead:'Read the poem'},
hi:{home:'होम',about:'परिचय',writings:'लेख',poetry:'कविता',language:'भाषा',heroNote:'सबके भीतर / तुम्हारे बिना',enter:'TASP को जानें',aboutKicker:'TASP के पीछे का विचार',introTitle:'एक पड़ताल<br><em>मनुष्य होने की।</em>',introText:'एक निजी बौद्धिक प्रयोगशाला, जहाँ हम अपने सोचने, महसूस करने, विश्वास रखने और अर्थ गढ़ने के तरीकों को खोजते हैं। यहाँ अवलोकन प्रश्न बनता है। प्रश्न पड़ताल बनता है। और पड़ताल ऐसा विचार बनती है जिसे हम साथ परख सकें।',introSecondary:'जिज्ञासुओं, चिंतन करने वालों और हर उस पाठक के लिए जिसे पढ़े हुए में अपना कुछ अंश मिलता है।',aboutMore:'TASP के बारे में और जानें',observe:'अवलोकन',question:'प्रश्न',investigate:'पड़ताल',understand:'समझ',subjectsKicker:'अपनी जिज्ञासा के साथ चलें',subjectsTitle:'आप कहाँ से शुरू करना चाहेंगे?',human:'मानवीय अनुभव',psychology:'मनोविज्ञान',philosophy:'दर्शन',spirituality:'अध्यात्म',writingsKicker:'कुछ विचार, कुछ ठहराव',selectedWritings:'लेख।',allWritings:'सभी लेख',threadsKicker:'अवलोकन, जो अभी खुल रहा है',threadsTitle:'एक क्षण से एक प्रश्न तक।',threadsText:'दो जुड़ी हुई पड़तालें—अवलोकन, प्रश्न और विकास के क्रम में।',poetryKicker:'जानने का एक अलग रास्ता',poetryTitle:'कुछ बातें<br><em>कविता</em> बनकर आती हैं।',poetryText:'उन बातों के लिए एक शांत जगह जिन्हें समझने से पहले महसूस किया जाता है।',visitPoetry:'कविता संग्रह में जाएँ',poemQuote:'कुछ अध्याय मुखर होते हैं।<br>कुछ मौन।<br>मौन हानि नहीं—<br><em>परिवर्तन है।</em>',poemCredit:'“एक दौर, अंत नहीं” से',footerLine:'ध्यान से देखें। ईमानदारी से प्रश्न करें।<br>निष्कर्ष से पहले समझें।',notion:'Notion पर पढ़ें',backTop:'ऊपर जाएँ ↑',read:'लेख पढ़ें',readThread:'पड़ताल पढ़ें',thread:'विचार-क्रम',stages:'अवलोकन · प्रश्न · विकास',minutes:'मिनट का पाठ',close:'पठन बंद करें',sourceNote:'मूल अंग्रेज़ी पाठ। इस रचना का पूरा अनुवाद तैयार किया जा रहा है।',originalPoem:'मूल कविता रोमन लिपि में हिंदी / उर्दू में है।',poemRead:'कविता पढ़ें'},
fr:{home:'Accueil',about:'À propos',writings:'Écrits',poetry:'Poésie',language:'Langue',heroNote:'EN CHACUN / SANS TOI',enter:'Découvrir TASP',aboutKicker:'L’IDÉE DERRIÈRE TASP',introTitle:'Une exploration de<br><em>la condition humaine.</em>',introText:'Un laboratoire intellectuel personnel pour explorer notre manière de penser, de ressentir, de croire et de donner du sens. Ici, une observation devient une question. Une question devient une investigation. Et cette investigation devient une réflexion à examiner ensemble.',introSecondary:'Pour les curieux, les contemplatifs et tous ceux qui retrouvent une part d’eux-mêmes dans leurs lectures.',aboutMore:'En savoir plus sur TASP',observe:'Observer',question:'Questionner',investigate:'Explorer',understand:'Comprendre',subjectsKicker:'SUIVEZ VOTRE CURIOSITÉ',subjectsTitle:'Par où souhaitez-vous commencer ?',human:'Expérience humaine',psychology:'Psychologie',philosophy:'Philosophie',spirituality:'Spiritualité',writingsKicker:'DES IDÉES À HABITER',selectedWritings:'Les écrits.',allWritings:'Tous les écrits',threadsKicker:'UNE OBSERVATION QUI SE DÉPLOIE',threadsTitle:'D’un instant à une question.',threadsText:'Deux réflexions suivies, chacune passant par Observer, Questionner et Développer.',poetryKicker:'UNE AUTRE FAÇON DE SAVOIR',poetryTitle:'Certaines choses<br>prennent forme en <em>poésie.</em>',poetryText:'Un espace plus calme pour ce que l’on ressent avant de le comprendre.',visitPoetry:'Découvrir le recueil',poemQuote:'Certains chapitres sont bruyants.<br>D’autres sont silencieux.<br>Le silence n’est pas une perte—<br><em>c’est une transformation.</em>',poemCredit:'EXTRAIT DE « UNE PHASE, PAS UNE FIN »',footerLine:'Observer avec attention. Questionner avec honnêteté.<br>Comprendre avant de conclure.',notion:'Explorer sur Notion',backTop:'Retour en haut ↑',read:'Lire l’essai',readThread:'Suivre la réflexion',thread:'Réflexion',stages:'OBSERVER · QUESTIONNER · DÉVELOPPER',minutes:'min de lecture',close:'Fermer la lecture',sourceNote:'Texte original en anglais. La traduction intégrale de ce texte est en préparation.',originalPoem:'Poème original en hindi / ourdou romanisé.',poemRead:'Lire le poème'},
es:{home:'Inicio',about:'Acerca de',writings:'Escritos',poetry:'Poesía',language:'Idioma',heroNote:'DENTRO DE TODOS / SIN TI',enter:'Descubrir TASP',aboutKicker:'LA IDEA DETRÁS DE TASP',introTitle:'Una exploración de<br><em>lo que significa ser humano.</em>',introText:'Un laboratorio intelectual personal para explorar cómo pensamos, sentimos, creemos y construimos sentido. Aquí, una observación se convierte en pregunta. Una pregunta, en investigación. Y esa investigación, en una reflexión que podemos examinar juntos.',introSecondary:'Para las personas curiosas, las reflexivas y quienes encuentran algo de sí mismas en lo que leen.',aboutMore:'Conocer mejor TASP',observe:'Observar',question:'Cuestionar',investigate:'Investigar',understand:'Comprender',subjectsKicker:'SIGUE TU CURIOSIDAD',subjectsTitle:'¿Por dónde te gustaría empezar?',human:'Experiencia humana',psychology:'Psicología',philosophy:'Filosofía',spirituality:'Espiritualidad',writingsKicker:'IDEAS EN LAS QUE DETENERSE',selectedWritings:'Los escritos.',allWritings:'Todos los escritos',threadsKicker:'UNA OBSERVACIÓN QUE SIGUE CRECIENDO',threadsTitle:'De un instante a una pregunta.',threadsText:'Dos reflexiones conectadas que avanzan por Observar, Cuestionar y Desarrollar.',poetryKicker:'OTRA FORMA DE CONOCER',poetryTitle:'Algunas cosas<br>llegan como <em>poesía.</em>',poetryText:'Un espacio más tranquilo para aquello que se siente antes de comprenderse.',visitPoetry:'Entrar en la colección',poemQuote:'Algunos capítulos son ruidosos.<br>Otros son silenciosos.<br>El silencio no es una pérdida—<br><em>es una transformación.</em>',poemCredit:'DE « UNA ETAPA, NO UN FINAL »',footerLine:'Observa con atención. Cuestiona con honestidad.<br>Comprende antes de concluir.',notion:'Explorar en Notion',backTop:'Volver arriba ↑',read:'Leer el ensayo',readThread:'Seguir la reflexión',thread:'Reflexión',stages:'OBSERVAR · CUESTIONAR · DESARROLLAR',minutes:'min de lectura',close:'Cerrar lectura',sourceNote:'Texto original en inglés. La traducción completa de esta obra está en preparación.',originalPoem:'Poema original en hindi / urdu romanizado.',poemRead:'Leer el poema'}
};
const titles={
'article-0002':{en:'The God We Construct',hi:'वह ईश्वर जिसे हम गढ़ते हैं',fr:'Le Dieu que nous construisons',es:'El Dios que construimos'},
'article-0003':{en:'Evidence, Me, or Responsibility',hi:'प्रमाण, मैं, या ज़िम्मेदारी',fr:'La preuve, moi, ou la responsabilité',es:'La evidencia, yo o la responsabilidad'},
'article-0001':{en:'Anatomy of a Sane Lie',hi:'एक विवेकपूर्ण झूठ की बनावट',fr:'Anatomie d’un mensonge raisonné',es:'Anatomía de una mentira sensata'},
'article-0005':{en:'When Love Becomes Identity — And Identity Becomes Emptiness',hi:'जब प्रेम पहचान बन जाता है—और पहचान खालीपन',fr:'Quand l’amour devient identité — et l’identité, vide',es:'Cuando el amor se convierte en identidad — y la identidad, en vacío'},
'article-0004':{en:'The Idea of God in a Fractured Mind',hi:'दरके हुए मन में ईश्वर की धारणा',fr:'L’idée de Dieu dans un esprit fissuré',es:'La idea de Dios en una mente fracturada'},
'article-0006':{en:'Being Surrounded by People but Being Invisible',hi:'लोगों से घिरे होकर भी अदृश्य होना',fr:'Entouré de monde, mais invisible',es:'Estar rodeado de gente y ser invisible'},
'thread-0001':{en:'The Space to Breathe',hi:'साँस लेने की जगह',fr:'L’espace pour respirer',es:'El espacio para respirar'},
'thread-0002':{en:'The Right to Let Go',hi:'छोड़ देने का अधिकार',fr:'Le droit de lâcher prise',es:'El derecho a soltar'},
'poem-phase':{en:'A Phase, Not an Ending',hi:'एक दौर, अंत नहीं',fr:'Une phase, pas une fin',es:'Una etapa, no un final'},
'poem-haqeeqat':{en:'Haqeeqat',hi:'हक़ीक़त',fr:'Haqeeqat — La réalité',es:'Haqeeqat — La realidad'},
overview:{en:'About TASP',hi:'TASP का परिचय',fr:'À propos de TASP',es:'Acerca de TASP'}
};
const descriptions={
'article-0002':{en:'What happens when the divine no longer resembles the world inside our minds? An inquiry into belief, expectation, and surrender.',hi:'जब दिव्यता हमारे मन की दुनिया जैसी नहीं रहती, तब क्या होता है? विश्वास, अपेक्षा और समर्पण की पड़ताल।',fr:'Que se passe-t-il lorsque le divin ne ressemble plus au monde que nous portons en nous ? Une réflexion sur la croyance, l’attente et l’abandon.',es:'¿Qué ocurre cuando lo divino deja de parecerse al mundo que llevamos dentro? Una reflexión sobre la creencia, las expectativas y la entrega.'},
'article-0003':{en:'Who am I becoming on the way? Creation, gratitude, and the responsibility of carrying a life.',hi:'रास्ते में मैं कौन बन रहा हूँ? सृजन, कृतज्ञता और जीवन सँभालने की ज़िम्मेदारी।',fr:'Qui suis-je en train de devenir ? La création, la gratitude et la responsabilité de porter une vie.',es:'¿En quién me estoy convirtiendo? La creación, la gratitud y la responsabilidad de llevar una vida.'},
'article-0001':{en:'When we step away from the truth, what are we really trying to protect?',hi:'जब हम सच से हटते हैं, वास्तव में किसकी रक्षा करना चाहते हैं?',fr:'Lorsque nous nous éloignons de la vérité, que cherchons-nous vraiment à protéger ?',es:'Cuando nos apartamos de la verdad, ¿qué intentamos proteger realmente?'},
'article-0005':{en:'The quiet boundary between loving someone and asking them to carry our entire sense of self.',hi:'किसी से प्रेम करने और उसे अपनी पूरी पहचान सँभालने को कहने के बीच की शांत सीमा।',fr:'La frontière discrète entre aimer quelqu’un et lui demander de porter toute notre identité.',es:'La frontera silenciosa entre amar a alguien y pedirle que sostenga toda nuestra identidad.'},
'article-0004':{en:'How our changing inner world shapes what we ask of God—and what we choose to believe.',hi:'हमारा बदलता भीतरी संसार ईश्वर से हमारी माँगों और विश्वासों को कैसे गढ़ता है।',fr:'Comment notre monde intérieur transforme ce que nous demandons à Dieu et choisissons de croire.',es:'Cómo nuestro mundo interior transforma lo que pedimos a Dios y lo que elegimos creer.'},
'article-0006':{en:'On presence, belonging, and the search for ourselves in the attention of others.',hi:'उपस्थिति, अपनेपन और दूसरों के ध्यान में स्वयं को खोजने पर।',fr:'Sur la présence, l’appartenance et la recherche de soi dans le regard des autres.',es:'Sobre la presencia, la pertenencia y la búsqueda de nosotros mismos en la atención ajena.'},
'thread-0001':{en:'When does helping become interference? On care that makes room instead of taking control.',hi:'मदद कब दख़ल बन जाती है? ऐसी परवाह जो नियंत्रण के बजाय जगह देती है।',fr:'Quand l’aide devient-elle ingérence ? Une attention qui laisse de l’espace au lieu de contrôler.',es:'¿Cuándo la ayuda se convierte en intromisión? Un cuidado que deja espacio en vez de controlar.'},
'thread-0002':{en:'Can a story matter deeply and still be allowed to end? On closure, release, and respect.',hi:'क्या कोई कहानी गहरी अहमियत रखते हुए भी समाप्त हो सकती है? समापन, मुक्ति और सम्मान पर।',fr:'Une histoire peut-elle compter profondément et pourtant prendre fin ? Sur l’apaisement, la libération et le respect.',es:'¿Puede una historia importar profundamente y aun así terminar? Sobre el cierre, la liberación y el respeto.'}
};
const articles=[{id:'article-0002',subject:'spirituality',tags:['spirituality','philosophy'],style:'featured'},{id:'article-0003',subject:'philosophy',tags:['philosophy','spirituality'],style:'second'},{id:'article-0001',subject:'psychology',tags:['psychology','philosophy'],style:''},{id:'article-0005',subject:'human',tags:['human','psychology'],style:''},{id:'article-0004',subject:'spirituality',tags:['spirituality','psychology'],style:''},{id:'article-0006',subject:'human',tags:['human','psychology'],style:'wide'}];
let lang='en',subject=null,opened=null;
const $=s=>document.querySelector(s);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const tr=k=>copy[lang][k]||copy.en[k];
function estimate(id){return Math.max(1,Math.ceil((window.TASP_CONTENT.en[id]||'').split(/\s+/).length/210))}
function cards(){
 $('#article-grid').innerHTML=articles.filter(a=>!subject||a.tags.includes(subject)).map(a=>{let heading=`<h3>${esc(titles[a.id][lang])}</h3>`,desc=`<p>${esc(descriptions[a.id][lang])}</p>`,link=`<button class="card-link" data-read="${a.id}" aria-label="${esc(tr('read')+': '+titles[a.id][lang])}">${esc(tr('read'))}</button>`;return `<article class="article-card ${a.style} reveal"><div class="article-meta"><span>${esc(tr(a.subject))} · ${estimate(a.id)} ${esc(tr('minutes'))}</span><span class="number">${a.id.slice(-4)}</span></div>${a.style==='featured'?'<div class="feature-orbit" aria-hidden="true"></div><div class="article-copy">'+heading+desc+link+'</div>':a.style==='wide'?heading+'<div class="wide-bottom">'+desc+link+'</div>':heading+desc+link}</article>`}).join('');
 $('#thread-grid').innerHTML=['thread-0001','thread-0002'].map(id=>`<article class="thread-card"><div class="article-meta"><span>${esc(tr('thread'))}</span><span class="number">${id.slice(-4)}</span></div><h3>${esc(titles[id][lang])}</h3><p>${esc(descriptions[id][lang])}</p><span class="stages">${esc(tr('stages'))}</span><button data-read="${id}" aria-label="${esc(tr('readThread')+': '+titles[id][lang])}"><span class="sr-only">${esc(tr('readThread'))}</span></button></article>`).join('');
 $('#reset-filter').hidden=!subject;$('#filter-status').textContent=subject?tr(subject):'';
}
function setLanguage(value){lang=value;document.documentElement.lang=lang;document.querySelectorAll('[data-i18n]').forEach(el=>el.innerHTML=tr(el.dataset.i18n));$('#language').setAttribute('aria-label',tr('language'));$('#close-reader').setAttribute('aria-label',tr('close'));cards();if(opened)renderReader(opened);}
function format(text,poem=false){
 let safe=esc(text.replace(/\*\*TASP[^\n]*\n/g,'').replace(/^## [^\n]*\n/,''));
 safe=safe.replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>');
 if(poem)return '<div class="poem-body">'+safe+'</div>';
 return safe.split(/\n\s*\n/).map(block=>{if(/^### /.test(block))return '<h2>'+block.replace(/^### /,'')+'</h2>';if(/^## /.test(block))return '<h2>'+block.replace(/^## /,'')+'</h2>';if(block.split('\n').every(l=>l.startsWith('- ')))return '<ul>'+block.split('\n').map(l=>'<li>'+l.slice(2)+'</li>').join('')+'</ul>';return '<p>'+block.replace(/^### (.+)$/gm,'<strong>$1</strong>')+'</p>'}).join('');
}
function renderReader(id){
 if(id==='poetry'){$('#reader-label').textContent=tr('poetry');$('#reader-body').innerHTML=`<h1 id="reader-title">${esc(tr('poetry'))}</h1>`+['poem-phase','poem-haqeeqat'].map(key=>`<div class="collection-item"><button data-read="${key}">${esc(titles[key][lang])} ↗</button><p>${esc(tr('poemRead'))}</p></div>`).join('');return;}
 const translated=window.TASP_CONTENT[lang]?.[id];let text=translated||window.TASP_CONTENT.en[id]||'';
 $('#reader-label').textContent=id==='overview'?tr('about'):id.startsWith('poem')?tr('poetry'):tr('writings');
 let note=lang!=='en'&&!translated?tr('sourceNote'):id==='poem-haqeeqat'&&lang==='en'?tr('originalPoem'):'';
 const isPoem=id.startsWith('poem');
 if(lang==='en'||!translated){const title=titles[id].en; text=text.replace(new RegExp('^'+title.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'[\\s–—-]*'), '');}
 $('#reader-body').innerHTML=`<h1 id="reader-title">${esc(titles[id][lang])}</h1>${note?'<p class="reader-note">'+esc(note)+'</p>':''}<div lang="${translated?lang:'en'}">${format(text,isPoem)}</div>`;
}
function openReader(id){opened=id;renderReader(id);if(!$('#reader').open)$('#reader').showModal();document.body.classList.add('reading');$('#reader').scrollTop=0;}
function closeReader(){$('#reader').close();document.body.classList.remove('reading');opened=null;}
document.addEventListener('click',e=>{const read=e.target.closest('[data-read]');if(read)openReader(read.dataset.read);const filter=e.target.closest('[data-subject]');if(filter){subject=filter.dataset.subject;cards();$('#writings').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});}});
$('#language').addEventListener('change',e=>setLanguage(e.target.value));$('#reset-filter').addEventListener('click',()=>{subject=null;cards()});$('#open-poetry').addEventListener('click',()=>openReader('poetry'));$('#close-reader').addEventListener('click',closeReader);$('#reader-home').addEventListener('click',closeReader);$('#reader').addEventListener('close',()=>{document.body.classList.remove('reading');opened=null});
const navLinks=[...document.querySelectorAll('.site-header nav a')];navLinks.forEach(a=>a.addEventListener('click',()=>{navLinks.forEach(l=>l.classList.toggle('active',a===l))}));
setLanguage('en');
